"""empty message

Revision ID: 110337ca53cb
Revises: 583f61635adf
Create Date: 2023-05-14 18:39:07.077394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110337ca53cb'
down_revision = '583f61635adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_contest',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('contest_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hpassword', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hpassword')

    op.drop_table('user_contest')
    # ### end Alembic commands ###
