"""empty message

Revision ID: 56989b544f9b
Revises: 0063cb117047
Create Date: 2023-05-15 18:09:21.829783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56989b544f9b'
down_revision = '0063cb117047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=36), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
