"""empty message

Revision ID: 583f61635adf
Revises: 
Create Date: 2023-05-13 19:41:57.740895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583f61635adf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.drop_constraint('professors_team_id_fkey', type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('professors_team_id_fkey', 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###
