"""empty message

Revision ID: 5ebccb15b672
Revises: 56dab77f274e
Create Date: 2023-05-15 21:36:53.834866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebccb15b672'
down_revision = '56dab77f274e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_constraint('board_member_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['m_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('board_member_id_fkey', 'users', ['member_id'], ['id'])
        batch_op.alter_column('member_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
