"""empty message

Revision ID: 618e4bddd62e
Revises: 
Create Date: 2023-04-26 18:04:22.051560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618e4bddd62e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=True),
    sa.Column('codeforces_handle', sa.String(length=30), nullable=True),
    sa.Column('atcoder_handle', sa.String(length=30), nullable=True),
    sa.Column('vjudge_handle', sa.String(length=30), nullable=True),
    sa.Column('fecha_de_nacimiento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
